### ISSUE TITLE
Add a 404 Not found page on same template

### ISSUE THREAD

**Issue by shreyasbapat** [shreyasbapat/shreyasbapat.github.io#1]

**Comment by victorjordan95** [comment]
Hey! I'm in :)

**Comment by shreyasbapat** [comment]
Hi! @victorjordan95 ! Thanks! Will wait for the PR. DO post the screenshots. (2) One on smaller device and one on larger. (Just resize the browser)

**Comment by victorjordan95** [comment]
Sure! I hope you like :)

**Comment by shreyasbapat** [comment]
Closed in #2
